### ISSUE TITLE
os.environment.get can have defaults

### ISSUE THREAD

**Issue by cgartner** [BDizzle/ccwf#1]
https://github.com/BDizzle/ccwf/blob/053ee5dcf86374d2d78d6e27059ca446e2b51067/sync.py#L10

You can set defaults for some of the environment variables if you want to trim down on what the user needs to add: `max_results = os.environ.get('ccwf_max_results', 30)`

**Comment by BDizzle** [comment]
@cgartner Sweet, thanks for the tip!
